

<?php


    $host = 'localhost';
$dbname = 'ktenant';
$username = 'root';
$password = '';
echo "hello world";
try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password);
    // Set PDO error mode to exception
    echo "Connected: " ;
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    echo "Connection failed: " . $e->getMessage();
}

/*
require_once 'system/landlord/vendor/autoload.php'; // Include Stripe PHP library

if (isset($_POST['stripeToken'])) {
    // Set your Stripe secret key
    \Stripe\Stripe::setApiKey('sk_test_aNvCJuR5OBWv4rB6o40u2MfL');

    // Get the token generated by the Stripe.js
    $token = $_POST['stripeToken'];

    try {
    // Create a charge
    $charge = \Stripe\Charge::create([
        'amount' => 1000, // Amount in cents
        'currency' => 'usd',
        'description' => 'Example Charge',
        'source' => $token,
    ]);

    // Payment successful
    echo 'Payment successful! Charge ID: ' . $charge->id;
    } catch (\Stripe\Exception\CardException $e) {
    // Payment failed
    echo 'Payment failed. Error: ' . $e->getMessage();
    }
}

*/


?>

