<?php

require_once '../landlord/vendor/autoload.php'; // Include Stripe PHP library

if (isset($_POST['stripeToken'])) {
    // Set your Stripe secret key
    \Stripe\Stripe::setApiKey('sk_test_aNvCJuR5OBWv4rB6o40u2MfL');

    // Get the token generated by the Stripe.js
    $token = $_POST['stripeToken'];
    
    // Get the amount value
    $amount = $_POST['amount'];

    try {
        // Create a charge
        $charge = \Stripe\Charge::create([
            'amount' => $amount * 100, // Convert amount to cents
            'currency' => 'mwk',
            'description' => 'Example Charge',
            'source' => $token,
        ]);

        // Payment successful
      //  echo 'Payment successful! Charge ID: ' . $charge->id;
      
       
      
        echo '<script>openModal("success");</script>';
    } catch (\Stripe\Exception\CardException $e) {
        // Payment failed
        echo 'Payment failed. Error: ' . $e->getMessage();
    }
}
?>
