<?php

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "ktenant";
$conn = null;
session_start();
echo $_SESSION["USER_ID"];
try
{
    $conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
    echo "connectd";
    // set the PDO error mode to exception
    $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
}
catch(PDOException $e)
{
    echo $sql . "<br>" . $e->getMessage();
}

function getContractDetails($id, $conn)
{
    $stmt = $conn->query("SELECT * FROM `contract` WHERE user_id ='$id'");
    $contract = $stmt->fetch(PDO::FETCH_OBJ);

    if (!empty($contract))
    {
        return $contract;
    }
    else
    {
        return null;
    }

}

require_once '../landlord/vendor/autoload.php'; // Include Stripe PHP library
if (isset($_POST['stripeToken']))
{
    // Set your Stripe secret key
    \Stripe\Stripe::setApiKey('sk_test_aNvCJuR5OBWv4rB6o40u2MfL');

    // Get the token generated by the Stripe.js
    $token = $_POST['stripeToken'];

    // Get the amount value
    $amount = $_POST['amount'];

    try
    {
        // Create a charge
        $charge = \Stripe\Charge::create(['amount' => $amount * 100, // Convert amount to cents
        'currency' => 'mwk', 'description' => 'Example Charge', 'source' => $token, ]);

        // Payment successful
        //  echo 'Payment successful! Charge ID: ' . $charge->id;
        $contract = getContractDetails($_SESSION["USER_ID"], $conn);

        if (isset($_SESSION["USER_ID"]))
        {

            $sql = "INSERT INTO payment (username, user_id, contract_id, payment_amount ,payment_type) VALUES ('John', 'Doe', 'wrwr3oerweeowwe','100000','card')";
            echo "insert block";
             $conn->exec($sql);
            // echo "New record created successfully";
            

            if (!$contract == null)
            {

                $userid = $_SESSION["USER_ID"];
                $contract_id = $contract->contract_id;
                $payment_amount = "100000";
                $payment_type = "card";

                $sql = "INSERT INTO payment (username, user_id, contract_id, payment_amount ,payment_type) VALUES ('$username', '$userid', '$contract_id','$amount','card')";
                echo "Payment successful, Added to Records";
                print_r($contract);
                $conn->exec($sql);
                
            }
            else
            {
                echo "contract dont exist";
            }

        }
        echo '<script>openModal("success");</script>';
    }
    catch(\Stripe\Exception\CardException $e)
    {
        // Payment failed
        echo 'Payment failed. Error: ' . $e->getMessage();
    }
}
?>
